---
title: Hỗ trợ Lớp 6/7 TK
timezone: Asia/Ho_Chi_Minh
collections:
  posts:
    title: Posts
    output: true
  sets:
    title: Sets
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
- scope:
    path: ''
    type: sets
  values:
    _hide_content: true
- scope:
    path: index.html
  values:
    body_class: show_hero_search
url: http://hotro.lop67.tk
baseurl: 
google_analytics_key: 
disqus_shortname: 
newsletter_action: 
logo: "/siteicon.png"
description: Trung tâm hỗ trợ dành cho người dùng Lớp 6/7 TK
author:
  name: 
  email: 
  twitter: 
social:
  name: 
  links: 
permalink: "/:categories/:title/"
plugins:
- jekyll-extract-element
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-archives
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
jekyll-archives:
  enabled:
  - categories
social_icons:
- Facebook
- Google Plus
- Instagram
- LinkedIn
- Pinterest
- Tumblr
- Twitter
- YouTube
- Email
- RSS
types:
- Document
- Video
_comments: 
